### ISSUE TITLE
trim() using ImageMagick 7

### ISSUE THREAD

**Issue by pl38** [Intervention/image#1058] opened 2020-11-16 15:39 UTC
**intervention/image** v2.5.1
**intervention/imagecache** v2.5
**laravel/framework** v8.14.0
**php** v7.4.12
**ImageMagick** 7.0.10-38 Q16 x86_64

I have added ImageMagick to a new Laravel install and am using code that has worked under Laravel and ImageMagick 6 (I cannot remember the actual version).

```
Image::make($pathToImage)
//    ->trim()
     ->sharpen(0)
    ->blur(0)
    ->brightness(0)
    ->contrast(0)
    ->resize(
        3000,
        3000,
        static function ($constraint) {
            $constraint->aspectRatio();
        }
     )
    ->resizeCanvas(3000, 3000, 'bottom')
    ->save($newFilename . '.jpg')
    ->encode('jpg', 85);

```

Using the new versions `->trim()` creates a blank image whereas before it trimmed as expect. 

Removing `->trim()`, and all the other commands work perfectly.

Has anyone seen this before or could offer some suggestions?

**Comment by elazar** [comment] 2021-03-17 23:28
This also appears to be the case with ImageMagick 7.0.11-3 Q16 x86_64.

**Comment by elazar** [comment] 2021-03-18 17:36
This may be a duplicate of #737.

**Closed** 2021-11-05 11:05 UTC
