### ISSUE TITLE
Hello Dear any one can help me?  

### ISSUE THREAD

**Issue by ArmanKT** [Intervention/image#1003] opened 2020-01-24 08:18 UTC
Hello dear  how can i put my own image, on this image frame using php GD library.  is it possible with intervention library ?? any on can help me?
like https://photofunia.com 

![qyr9w4_o](https://user-images.githubusercontent.com/38861462/73054214-0bba1000-3eb4-11ea-948f-759342e2b20e.jpg)
![3l8ico_o](https://user-images.githubusercontent.com/38861462/73054218-0eb50080-3eb4-11ea-965b-054e57195157.jpg)

**Comment by ausi** [comment] 2020-01-24 11:47
Duplicate of https://github.com/avalanche123/Imagine/issues/735

**Comment by ArmanKT** [comment] 2020-01-29 16:56
> Duplicate of [avalanche123/Imagine#735](https://github.com/avalanche123/Imagine/issues/735)

I need solution boss

**Closed** 2023-12-08 18:37 UTC
