### ISSUE TITLE
gd resize, no longer transparent

### ISSUE THREAD

**Issue by u007** [Intervention/image#457] opened 2015-11-16 16:46 UTC
Hi,

after calling resize,
any draw of rectangle with 
$draw->background('rgba(255, 255, 255, 0.5)'); 

does not generate alpha 0.5, but no transparent.

**Comment by olivervogel** [comment] 2015-11-16 17:09
Of course you have to output a format, which supports trancparency.

**Comment by u007** [comment] 2015-11-16 17:16
Hi

Yes, I've output PNG,
Still same. If I did not resize it, the transparent works.

**Comment by u007** [comment] 2015-11-17 03:40
same seems to happen with crop

**Comment by wwendorf** [comment] 2015-12-11 18:28
Yep, same is happening with crop, but in my case it is forcing it to a background of black.  Any fix for this in the works?

**Comment by eness** [comment] 2016-08-29 10:27
+1 for black background issue.

**Comment by lawrencedudley** [comment] 2017-04-27 23:38
Interestingly, if you use GD you get a black background. If you use Imagemagick, you get a smaller image than you asked for from crop - the black pixels just get cut off.

**Comment by dhensby** [comment] 2017-09-07 14:20
I'm having this problem too :(

**Comment by dhensby** [comment] 2017-09-11 19:39
Right, so I've investigated and the problem I had was that I was cloning the image object. This calls `Gd\Driver@cloneCore` which creates a new GD image resource. By default that resource has a black background. I'm not sure if the core functions the others have reported did or didn't clone the core or maybe you've been cloning the core too? But my patch is at #776

**Comment by olivervogel** [comment] 2024-01-07 11:30
Possible duplicate of https://github.com/Intervention/image/issues/1251

**Closed by olivervogel** 2024-01-07 11:30 UTC
